######## ENTER PARAMETERS HERE ##########

Temperature = 255.93;    # particles / flow initial and boundary temperature
Velocity = 102.8;        # particles / flow initial and boundary velocity (x-component)
Duration = 420.0;        # duration of the experiment
ParcelsPerSecond = 1260; # parcels per second
MassTotal = 23.79;       # total mass of water in system during all time
Diameter = 20e-6;        # particles diameter

## Note that
## LWC = MassTotal / (Duration * S * Velocity)
## in this case S = 0.23 * 0.1
#########################################


with open("caseConditions", "w") as file_out:
    file_out.write('/*=== DO NOT EDIT THIS FILE! GO TO caseConditionsScript.py! ===*/\n\n');
    file_out.write('Temperature   ' + str(Temperature) + ";\n");
    file_out.write('Velocity   ' + str(Velocity) + ";\n");
    file_out.write('Duration   ' + str(Duration) + ";\n");
    file_out.write('ParcelsPerSecond   ' + str(ParcelsPerSecond) + ";\n");
    file_out.write('MassTotal   ' + str(MassTotal) + ";\n");
    file_out.write('Diameter   ' + str(Diameter) + ";\n");

with open('constant/parcelInjectionProperties.template') as file_in:
    text = file_in.read();

#print(text);

text = text.replace("$Temperature",str(Temperature));
text = text.replace("$Velocity",str(Velocity));
text = text.replace("$Diameter",str(Diameter));

with open("constant/parcelInjectionProperties", "w") as file_out:
    file_out.write(text);
